project: 'FM-IRL-pick-noise'
program: fmirl/main.py
method: grid
name: Pick-FM-BC-2.25
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - --use-proper-time-limits
parameters:
  prefix:
    value: fm-bc
  alg:
    value: fm-bc
  experiment-name:
    value: fm-bc-2.25
  group-name:
    value: noise-2.25
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0
  normalize-env:
    value: False
  traj-load-path:
    value: ./expert_datasets/pick_10000.pt
  bc-num-epochs:
    value: 10000
  eval-num-processes:
    value: 20
  traj-frac:
    value: 0.5
  traj-val-ratio:
    value: 0.2
  noise-ratio:
    value: 2.25
  goal-noise-ratio:
    value: 2.25
  seed:
    values: [1,2,3,4]


